parameters:
  serviceUrl: 

jobs:
- job: BuildAndTest
  displayName: Build and Test

  pool:
    vmImage: 'Ubuntu-16.04'
  
  steps:
  - download: current
    artifact: extension

  # Upload the extension
  - script: |
      # Display command output and fail immediately on any errors
      set -e -x

      # Install the latext command line task for publishing extensions
      sudo npm install -g tfx-cli

      # Log in to Azure DevOps with tfx
      tfx login \
        --token $SYSTEM_ACCESSTOKEN
        --service-url ${{ parameters.serviceUrl }}

      # Publish the extension
      tfx extension publish
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
    displayName: Build, test and package the Task
