parameters:
  serviceUrl: 

jobs:
- job: BuildAndTest
  displayName: Build and Test

  pool:
    vmImage: 'Ubuntu-16.04'
  
  steps:
  # Do not clone from git for this job
  - checkout: none

  # Download the published extension artifact to deploy
  - download: current
    artifact: extension

  # Publish the extension to Azure DevOps
  - script: |
      # Display command output and fail immediately on any errors
      set -e -x

      # Install the latext command line task for publishing extensions
      sudo npm install -g tfx-cli

      # Log in to Azure DevOps with tfx
      tfx login \
        --token $SYSTEM_ACCESSTOKEN
        --service-url ${{ parameters.serviceUrl }}
        --no-prompt

      # Publish the extension
      tfx extension publish --no-prompt
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
    workingDirectory: $(Pipeline.Workspace)/extension
    displayName: Build, test and package the Task
