trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - readme.md

pr:
  autoCancel: true

# Build and Test
stages:
- stage: Build
  displayName: Build and Test Tasks
  jobs:
  - template: azure-pipelines-extension-build.yml

# Staging Extension release
- stage: Staging
  jobs:
  - template: azure-pipelines-extension-release.yml
    parameters:
      serviceUrl: https://dev.azure.com/jlorich
