parameters:
  workingDirectory:

steps:
- script: |
    # Display command output and fail immediately on any errors
    set -e -x

    # Update package version to build number
    sed -i 's/{{PACKAGE_VERSION}}/$(Build.BuildNumber)/g' package.json

    # Update task major version
    sed -i 's/{{MAJOR_VERSION}}/$(GitVersion.Major)/g' task.json

    # Update task minor version
    sed -i 's/{{MINOR_VERSION}}/$(GitVersion.Minor)/g' task.json

    # Update task patch version
    sed -i 's/{{PATCH_VERSION}}/$(GitVersion.Patch)/g' task.json
  workingDirectory: ${{ parameters.workingDirectory }}
  displayName: Set Package and Task Versions

- script: |
    # Install NPM Packages
    npm install
    
    # Build typescript
    tsc --build
    
    # Ensure the destination path exists
    mkdir -p $(Build.StagingDirectory)/Tasks/

    # Copy all task files to the staging output path
    rsync -avr . \
      --exclude=./* \
      --include=./node_modules \
      --include=./package.json \
      --include=./package-lock.json \
      --include=./task.json \
      $(Build.StagingDirectory)/Tasks/  
  workingDirectory: ${{ parameters.workingDirectory }}
  displayName: Build, test, and package the Task
